import uzb from "../icons/uzb.svg"
import rus from "../icons/rus.svg"
import ukd from "../icons/ukd.svg"

export const language = {
    uz:{
        FLAG: uzb,
        N0:"Asosiy saxifa",
        N1:"Biz haqimizda",
        N2:"O'quv yili",
        N4:"Qabul",
        N5:"Yangiliklar",
        N6:"Maktab hayoti",
        VIDEO:"Video",
        NO_FOTO:"Rasm yo'q",
        CONTACT_US: "Biz bilan bog'lanish",
        CONTACT_US_INFO: "Sizning telefon raqamlaringiz",
        CONTACT_US_BTN: "Telefon raqamingizni qoldiring",
        FALLOW: "Bizni kuzatib boring",
        OQITUVCHILAR: "Bizning o'qituvchilarimiz",
        NASHA_MISSIYA: "Biz haqimizda",
        OLIMPIADA: "Olimpiada natijalari",
        MEROPRIYATIYA: "Tadbirlar",
        POISK:"Veb-saytdan qidirish",
        GALEREYA:"Fotogalereya",
        ZAYAVKA: "Maktabda qatnashmaslik",
        ZAYAVKA_NAME: "Ismingiz va Familiyangiz",
        ZAYAVKA_CLAS: "Sizning sinfingiz",
        ZAYAVKA_INFO: "Sabab",
        SHOW_ALL: "Hammasini ko'rsatish",
        MENYU: "Maktab menyusi",
        ZAVTRAK: "Nonushta",
        OBED: "Tushlik",
        UJIN: "Kechki ovqat",
        FORMA: "Maktab formasi",
        KALENDAT: "Maktab kalendar",
        MAKTAB_HAYOTI: "Maktab hayoti",
        SPRAVOCHNIK: "Qo'llanma",
        PODROBNO:"Batafsil",
        PROTSES: "Qabul jarayoni",
        NEWS: "Yangiliklar",
        TEACHERS: "O'qituvchilar",
        RESOURCES: "Resurslar",
        SHARE: "Ulashish",
        MANZIL: <h1>Andijon shahar<br/>Nodira ko'chasi 1-uy</h1>,
    },
    ru:{
        FLAG: rus,
        N0:"Главный меню",
        N1:"О нас",
        N2:"Учебный год",
        N4:"Поступление",
        N5:"Новости",
        N6:"Школьная жизнь",
        VIDEO:"Видео",
        NO_FOTO:"Нет фотографий",
        CONTACT_US: "Связаться с нами",
        CONTACT_US_INFO: "Ваш телефон номера",
        CONTACT_US_BTN: "Оставить номер телефона",
        FALLOW: "Подписывайтесь на нас",
        OQITUVCHILAR: "Наши учителя",
        NASHA_MISSIYA: "О нас",
        OLIMPIADA: "Результаты олимпиады",
        MEROPRIYATIYA: "Мероприятия",
        POISK:"Поиск по веб сайту",
        GALEREYA:"Фотогалерея",
        ZAYAVKA: "Заявка о прогуле школы",
        ZAYAVKA_NAME: "Ваша имя и фамилия",
        ZAYAVKA_CLAS: "Ваш класс",
        ZAYAVKA_INFO: "Причина прогула",
        SHOW_ALL: "Показать все",
        MENYU: "Школьное меню",
        ZAVTRAK: "Завтрак",
        OBED: "Обед",
        UJIN: "Ужин",
        FORMA: "Школьная форма",
        KALENDAT: "Школьный календарь",
        MAKTAB_HAYOTI: "Школьная жизнь",
        SPRAVOCHNIK: "Справочник",
        PODROBNO:"Подробнее",
        PROTSES: "Процесс поступления",
        NEWS: "Новости",
        TEACHERS: "Учителя",
        RESOURCES: "Ресурсы",
        SHARE: "Поделиться",
        MANZIL: <h1>Город Андижан<br/>Улица Нодира 1-дом</h1>,
    },
    en:{
        FLAG: ukd,
        N0:"Main menu",
        N1:"About us",
        N2:"Academic year",
        N4:"Admission",
        N5:"News",
        N6:"School life",
        VIDEO:"Video",
        NO_FOTO:"No photos",
        CONTACT_US: "Contact us",
        CONTACT_US_INFO: "Your phone numbers",
        CONTACT_US_BTN: "Leave your phone number",
        FALLOW: "Follow Us",
        OQITUVCHILAR: "Our teachers",
        NASHA_MISSIYA: "About us",
        OLIMPIADA: "Results of the Olympiad",
        MEROPRIYATIYA: "Activities",
        POISK:"Search the website",
        GALEREYA:"Gallery",
        ZAYAVKA: "Absenteeism from school",
        ZAYAVKA_NAME: "Your name",
        ZAYAVKA_CLAS: "Your class",
        ZAYAVKA_INFO: "Cause",
        SHOW_ALL: "Show all",
        MENYU: "School menu",
        ZAVTRAK: "Breakfast",
        OBED: "Lunch",
        UJIN: "Dinner",
        FORMA: "School uniform",
        KALENDAT: "School calendar",
        MAKTAB_HAYOTI: "School life",
        SPRAVOCHNIK: "Handbook",
        PODROBNO:"More",
        PROTSES: "Admission process",
        NEWS: "News",
        TEACHERS: "Teachers",
        RESOURCES: "Resources",
        SHARE: "Share",
        MANZIL: <h1>Andijan city<br/>Nodira street 1-house</h1>,
    }
}