import uzb from "../icons/uzb.svg"
import rus from "../icons/rus.svg"
import usa from "../icons/usa.svg"

export const language = {
    uz:{
        MAIN_NT1:"ZMB",
        MAIN_NT2:" - bolangizga yoqadigan joy",
        FLAG: uzb,
        N1:"Bizning maktab",
        N2:"O'quv yili",
        N3:"Akademik fanlar",
        N4:"Qabul",
        N5:"Yangiliklar",
        N6:"Maktab hayoti",
        N7:"Covid-19",
        CONTACT_US: "Biz bilan bog'lanish",
        CONTACT_US_INFO: "Sizning telefon raqamlaringiz",
        CONTACT_US_BTN: "Telefon raqamingizni qoldiring",
        FALLOW: "Bizni kuzatib boring",
        OQITUVCHILAR: "Bizning o'qituvchilarimiz",
        NASHA_MISSIYA: "Bizning maqsadimiz",
        MEROPRIYATIYA: "Tadbirlar",
        KTO_MI: "Biz kimmiz",
        POISK:"Veb-saytdan qidirish",
        GALEREYA:"Fotogalereya",
        ZAYAVKA: "Maktabda qatnashmaslik",
        ZAYAVKA_NAME: "Ismingiz va Familiyangiz",
        ZAYAVKA_CLAS: "Sizning sinfingiz",
        ZAYAVKA_INFO: "Sabab",
        SHOW_ALL: "Hammasini ko'rsatish",
        MENYU: "Maktab menyusi",
        ZAVTRAK: "Nonushta",
        OBED: "Tushlik",
        UJIN: "Kechki ovqat",
        FORMA: "Maktab formasi",
        KALENDAT: "Maktab kalendar",
        MAKTAB_HAYOTI: "Maktab hayoti",
        SPRAVOCHNIK: "Qo'llanma",
        PODROBNO:"Batafsil",
        PROTSES: "Qabul jarayoni",
        PR1: <p>Kirish <span>so'rovnomasini</span> to'ldiring</p>,
        PR2: <p>Bizning <span>elektron pochta manzilimizga</span> so'rovnoma yuboring</p>,
        PR3:"3 kun ichida javob olasiz",
        NEWS: "Yangiliklar",
        COVID_1:"Alomatlari",
        COVID_1_1:"Isitma, quruq yo'tal, charchoq.",
        COVID_1_2:"Kamroq tarqalgani tanadagi og'riqlar, tomoq og'rig'i, diareya, kon'yunktivit, bosh og'rig'i, ta'm va / yoki hidning yo'qolishi, teri toshmasi yoki barmoqlar yoki oyoq barmoqlarining rangi o'zgarishi. Hidning yo'qolishi juda o'ziga xos xususiyatga ega va isitma yoki yo'talsiz sodir bo'lishi mumkin. Hid yoki ta'mni yo'qotishning o'rtacha davomiyligi taxminan 8 kunni tashkil qiladi . Hidni yo'qotish, dastlabki hisob-kitoblarga ko'ra, koronavirus bilan kasallanganlarning 80 foizida sodir bo'ladi.",
        COVID_2_1:"JSST ma'lumotlariga ko'ra, tibbiy yordam talab qiladigan xavfli alomatlar",
        COVID_2_2:<div> <p>Nafas qisilishi yoki nafas qisilishi</p> <p>Ko'krak og'rig'i yoki siqish hissi</p> <p>Harakat qilish yoki gapirish qobiliyatini yo'qotish.</p></div>,
        COVID_3:"Oldini olish",
        COVID_3_1:"Jahon sog'liqni saqlash tashkiloti (JSST) Covid-19 yuqtirish xavfini kamaytirish bo'yicha umumiy tavsiyalar berdi",
        COVID_3_2:<div> <p>Qo'lingizni sovun yoki spirtli ichimlik bilan muntazam yuving;</p> <p>Yo'tal yoki hapşırma paytida burun va og'zingizni egilgan tirsak yoki bir marta ishlatiladigan salfetka bilan yoping, keyin qo'lni majburiy yuvish;</p> <p>Jamoat joylarida boshqa odamlar bilan 1 metr masofani saqlang, ayniqsa ularda nafas olish belgilari yoki isitma bo'lsa;</p> <p>Iloji bo'lsa, qo'llaringiz bilan burun, og'iz va ko'zlarga tegmang;</p> <p>Agar sizda isitma, yo'tal yoki nafas qisilishi bo'lsa, shifokorga murojaat qiling.</p> </div>,
        COVID_4_1:"2021-yil mart oyi holatiga ko‘ra, COVID-19 uchun hech qanday dalilga asoslangan davolash ishlab chiqilmagan",
        COVID_4_2:"Viruslarga qarshi antibiotiklar foydasiz va davolashda foydali emas. Biroq, agar bakterial ikkilamchi infektsiya aniqlansa, ular buyurilishi mumkin. Ko'pgina bemorlar simptomatik va qo'llab-quvvatlovchi terapiyani oladilar. O'tkir nafas etishmovchiligi bo'lgan bemorlarni davolashning asosiy vazifasi tananing kislorod bilan ta'minlanishini etarli darajada ushlab turishdir, chunki kislorod etishmasligi hayotiy organlarning ishida qaytarilmas buzilishlarga va o'limga olib kelishi mumkin. Og'ir holatlarda davolanish tananing hayotiy funktsiyalarini saqlab qolishga qaratilgan.",
    },
    ru:{
        MAIN_NT1:"ZMB",
        MAIN_NT2:" - место где вашему ребёнку понравится",
        FLAG: rus,
        N1:"Наша школа",
        N2:"Учебный год",
        N3:"Учебные предметы",
        N4:"Поступление",
        N5:"Новости",
        N6:"Школьная жизнь",
        N7:"Covid-19",
        CONTACT_US: "Связаться с нами",
        CONTACT_US_INFO: "Ваш телефон номера",
        CONTACT_US_BTN: "Оставить номер телефона",
        FALLOW: "Подписывайтесь на нас",
        OQITUVCHILAR: "Наши учителя",
        NASHA_MISSIYA: "Наша миссия",
        MEROPRIYATIYA: "Мероприятия",
        KTO_MI: "Кто мы",
        POISK:"Поиск по веб сайту",
        GALEREYA:"Фотогалерея",
        ZAYAVKA: "Заявка о прогуле школы",
        ZAYAVKA_NAME: "Ваша имя и фамилия",
        ZAYAVKA_CLAS: "Ваш класс",
        ZAYAVKA_INFO: "Причина прогула",
        SHOW_ALL: "Показать все",
        MENYU: "Школьное меню",
        ZAVTRAK: "Завтрак",
        OBED: "Обед",
        UJIN: "Ужин",
        FORMA: "Школьная форма",
        KALENDAT: "Школьный календарь",
        MAKTAB_HAYOTI: "Школьная жизнь",
        SPRAVOCHNIK: "Справочник",
        PODROBNO:"Подробнее",
        PROTSES: "Процесс поступления",
        PR1:<p>Заполняете вступительную <span>анкету</span></p>,
        PR2:<p>Присылаете анкету на наш <span>email адресс</span></p>,
        PR3:"В течение 3 дней вы получите ответ",
        NEWS: "Новости",
        COVID_1:"Симптомы",
        COVID_1_1:"Лихорадка, сухой кашель, усталость.",
        COVID_1_2:"Менее часто встречаются ломота в теле, боль в горле, диарея, конъюнктивит, головная боль, потеря вкуса и (или) обоняния, кожная сыпь или изменение цвета пальцев рук или ног. Потеря обоняния является высоко специфичным симптомом и может наблюдаться без сопутствующих лихорадки или кашля. Медианная продолжительность потери обоняния или вкуса составляет примерно 8 дней. Потеря обоняния, по предварительным оценкам, происходит у 80 % заразившихся коронавирусом",
        COVID_2_1:"Согласно ВОЗ опасными симптомами, при которых необходима медицинская помощь, являются",
        COVID_2_2:<div> <p>Одышка или затруднённое дыхание,</p> <p>Боли в груди или ощущение её сдавливания,</p> <p>Потеря возможности двигаться или разговаривать.</p> </div>,
        COVID_3: "Прафилактика",
        COVID_3_1:"Всемирная организация здравоохранения (ВОЗ) дала общие рекомендации по снижению риска заражения Covid-19",
        COVID_3_2:<div> <p>Регулярно мыть руки с мылом или спиртосодержащим средством;</p> <p>При кашле или чихании прикрывать нос и рот согнутым локтем или одноразовой салфеткой с последующим обязательным мытьём рук;</p> <p>Соблюдать дистанцию в 1 метр по отношению к другим людям в общественных местах, особенно, если у них наблюдаются респираторные симптомы или повышенная температура;</p> <p>По возможности не трогать руками нос, рот и глаза;</p> <p>При наличии лихорадки, кашля и затруднённого дыхания обратиться в медицинское учреждение за помощью.</p> </div>,
        COVID_4_1:"По состоянию на март 2021 года не разработано основанного на доказательствах лечения COVID-19",
        COVID_4_2:"Антибиотики против вирусов бесполезны и не применяются в лечении. Однако они могут быть назначены в случае обнаружения бактериальной вторичной инфекции. В основном пациенты получают симптоматическую и поддерживающую терапию. Основной задачей лечения больных с острой дыхательной недостаточностью является поддержание достаточного уровня оксигенации организма, поскольку недостаток кислорода может привести к необратимым нарушениям в работе жизненно важных органов и летальному исходу. В тяжёлых случаях лечение направлено на поддержание жизненно важных функций организма.",
    },
    en:{
        MAIN_NT1:"ZMB",
        MAIN_NT2:" - a place where your child will like",
        FLAG: usa,
        N1:"Our school",
        N2:"Academic year",
        N3:"Academic subjects",
        N4:"Admission",
        N5:"News",
        N6:"School life",
        N7:"Covid-19",
        CONTACT_US: "Contact us",
        CONTACT_US_INFO: "Your phone numbers",
        CONTACT_US_BTN: "Leave your phone number",
        FALLOW: "Follow Us",
        OQITUVCHILAR: "Our teachers",
        NASHA_MISSIYA: "Our mission",
        MEROPRIYATIYA: "Activities",
        KTO_MI: "Who are we",
        POISK:"Search the website",
        GALEREYA:"Gallery",
        ZAYAVKA: "Absenteeism from school",
        ZAYAVKA_NAME: "Your name",
        ZAYAVKA_CLAS: "Your class",
        ZAYAVKA_INFO: "Cause",
        SHOW_ALL: "Show all",
        MENYU: "School menu",
        ZAVTRAK: "Breakfast",
        OBED: "Lunch",
        UJIN: "Dinner",
        FORMA: "School uniform",
        KALENDAT: "School calendar",
        MAKTAB_HAYOTI: "School life",
        SPRAVOCHNIK: "Handbook",
        PODROBNO:"More",
        PROTSES: "Admission process",
        PR1:<p>Fill out the introductory <span>form</span></p>,
        PR2:<p>Send a questionnaire to our <span>email address</span></p>,
        PR3:"You will receive a reply within 3 days",
        NEWS: "News",
        COVID_1:"Symptoms",
        COVID_1_1:"",
        COVID_1_2:"Less common are body aches, sore throat, diarrhea, conjunctivitis, headache, loss of taste and / or smell, skin rash, or discoloration of fingers or toes . Loss of smell is highly specific and can occur without concomitant fever or cough . The median duration of loss of smell or taste is approximately 8 days . Loss of smell, according to preliminary estimates, occurs in 80% of those infected with coronavirus",
        COVID_2_1:"According to WHO, dangerous symptoms that require medical attention are",
        COVID_2_2:<div> <p>Shortness of breath or shortness of breath</p> <p>Chest pain or a feeling of squeezing</p> <p>Loss of ability to move or speak.</p> </div>,
        COVID_3:"Prophylaxis",
        COVID_3_1:"The World Health Organization (WHO) has made general recommendations to reduce the risk of contracting Covid-19",
        COVID_3_2:<div> <p>Wash your hands regularly with soap or alcohol;</p> <p>When coughing or sneezing, cover your nose and mouth with a bent elbow or a disposable tissue, followed by mandatory hand washing;</p> <p>Maintain a distance of 1 meter in relation to other people in public places, especially if they have respiratory symptoms or fever;</p> <p>If possible, do not touch the nose, mouth and eyes with your hands;</p> <p>If you have a fever, cough, or shortness of breath, seek medical attention.</p> </div>,
        COVID_4_1:"No evidence-based treatment for COVID-19 has been developed as of March 2021",
        COVID_4_2:"Antibiotics against viruses are useless and not useful in treatment. However, they can be prescribed if a bacterial secondary infection is detected. Most patients receive symptomatic and supportive therapy. The main task of treating patients with acute respiratory failure is to maintain a sufficient level of oxygenation of the body, since a lack of oxygen can lead to irreversible disturbances in the functioning of vital organs and death. In severe cases, treatment is aimed at maintaining the vital functions of the body.",
    }
}