import uzb from "../icons/uzb.svg"
import rus from "../icons/rus.svg"
import usa from "../icons/usa.svg"

export const language = {
    uz:{
        MAIN_NT1:"ZMB",
        MAIN_NT2:" - bolangizga yoqadigan joy",
        FLAG: uzb,
        N1:"Bizning maktab",
        N2:"O'quv yili",
        N3:"Akademik fanlar",
        N4:"Qabul",
        N5:"Yangiliklar",
        N6:"Maktab hayoti",
        CONTACT_US: "Biz bilan bog'lanish",
        CONTACT_US_INFO: "Sizning telefon raqamlaringiz",
        CONTACT_US_BTN: "Telefon raqamingizni qoldiring",
        FALLOW: "Bizni kuzatib boring",
        OQITUVCHILAR: "Bizning o'qituvchilarimiz",
        NASHA_MISSIYA: "Bizning maqsadimiz",
        MEROPRIYATIYA: "Tadbirlar",
        KTO_MI: "Biz kimmiz",
        POISK:"Veb-saytdan qidirish",
        GALEREYA:"Fotogalereya",
        ZAYAVKA: "Maktabda qatnashmaslik",
        ZAYAVKA_NAME: "Ismingiz va Familiyangiz",
        ZAYAVKA_CLAS: "Sizning sinfingiz",
        ZAYAVKA_INFO: "Sabab",
        SHOW_ALL: "Hammasini ko'rsatish",
        MENYU: "Maktab menyusi",
        ZAVTRAK: "Nonushta",
        OBED: "Tushlik",
        UJIN: "Kechki ovqat",
        FORMA: "Maktab formasi",
        KALENDAT: "Maktab kalendar",
        MAKTAB_HAYOTI: "Maktab hayoti",
        SPRAVOCHNIK: "Qo'llanma",
    },
    ru:{
        MAIN_NT1:"ZMB",
        MAIN_NT2:" - место где вашему ребёнку понравится",
        FLAG: rus,
        N1:"Наша школа",
        N2:"Учебный год",
        N3:"Учебные предметы",
        N4:"Поступление",
        N5:"Новости",
        N6:"Школьная жизнь",
        CONTACT_US: "Связаться с нами",
        CONTACT_US_INFO: "Ваш телефон номера",
        CONTACT_US_BTN: "Оставить номер телефона",
        FALLOW: "Подписывайтесь на нас",
        OQITUVCHILAR: "Наши учителя",
        NASHA_MISSIYA: "Наша миссия",
        MEROPRIYATIYA: "Мероприятия",
        KTO_MI: "Кто мы",
        POISK:"Поиск по веб сайту",
        GALEREYA:"Фотогалерея",
        ZAYAVKA: "Заявка о прогуле школы",
        ZAYAVKA_NAME: "Ваша имя и фамилия",
        ZAYAVKA_CLAS: "Ваш класс",
        ZAYAVKA_INFO: "Причина прогула",
        SHOW_ALL: "Показать все",
        MENYU: "Школьное меню",
        ZAVTRAK: "Завтрак",
        OBED: "Обед",
        UJIN: "Ужин",
        FORMA: "Школьная форма",
        KALENDAT: "Школьный календарь",
        MAKTAB_HAYOTI: "Школьная жизнь",
        SPRAVOCHNIK: "Справочник",
    },
    en:{
        MAIN_NT1:"ZMB",
        MAIN_NT2:" - a place where your child will like",
        FLAG: usa,
        N1:"Our school",
        N2:"Academic year",
        N3:"Academic subjects",
        N4:"Admission",
        N5:"News",
        N6:"School life",
        CONTACT_US: "Contact us",
        CONTACT_US_INFO: "Your phone numbers",
        CONTACT_US_BTN: "Leave your phone number",
        FALLOW: "Follow Us",
        OQITUVCHILAR: "Our teachers",
        NASHA_MISSIYA: "Our mission",
        MEROPRIYATIYA: "Activities",
        KTO_MI: "Who are we",
        POISK:"Search the website",
        GALEREYA:"Gallery",
        ZAYAVKA: "Absenteeism from school",
        ZAYAVKA_NAME: "Your name",
        ZAYAVKA_CLAS: "Your class",
        ZAYAVKA_INFO: "Cause",
        SHOW_ALL: "Show all",
        MENYU: "School menu",
        ZAVTRAK: "Breakfast",
        OBED: "Lunch",
        UJIN: "Dinner",
        FORMA: "School uniform",
        KALENDAT: "School calendar",
        MAKTAB_HAYOTI: "School life",
        SPRAVOCHNIK: "Handbook",
    }
}